name: mvvm_contracts_impl
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  cupertino_icons: ^1.0.8
  default_ui_components:
    path: /Users/chidiebubeiroezindu/Developer/flutter_projects/default_ui_components
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  get_it: ^8.0.3
  go_router: ^15.1.1
  hive_ce: ^2.10.1
  json_annotation: ^4.9.0
  mockito: ^5.4.4
  provider: ^6.1.4
  shared_preferences: ^2.5.3

dev_dependencies:
  build_runner: ^2.4.13
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

  json_serializable: ^6.9.0

flutter:

  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
