// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:mvvm_contracts_impl/features/auth/data/models/admin_response_model.dart';
import 'package:mvvm_contracts_impl/features/auth/data/models/customer_response_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AdminResponseModelAdapter());
    registerAdapter(CustomerResponseModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AdminResponseModelAdapter());
    registerAdapter(CustomerResponseModelAdapter());
  }
}
